In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Stopping Voltages 400.csv")

In [3]:
df.head()

,filter,wavelength,initial_current,stopping_voltage,stopping_voltage_uncertainty
0,NaN,640,5.21,0.3113,0.0001
1,NaN,626,5.21,0.4073,0.0001
2,NaN,604,5.21,0.4929,0.0001
3,NaN,590,5.21,0.5669,0.0001
4,NaN,570,5.21,0.6306,0.0001

In [4]:
df.drop(columns=["filter"], inplace=True)

In [5]:
df.head()

   wavelength  initial_current  stopping_voltage  stopping_voltage_uncertainty
0         640             5.21            0.3113                        0.0001
1         626             5.21            0.4073                        0.0001
2         604             5.21            0.4929                        0.0001
3         590             5.21            0.5669                        0.0001
4         570             5.21            0.6306                        0.0001

In [ ]:
from scipy import constants as const


df["-e_delta_v"] = -const.e * (df["stopping_voltage"] * 1e-3)
df["c_over_lambda"] = const.c / (df["wavelength"] * 1e-9)

In [7]:
df.head()

,wavelength,initial_current,stopping_voltage,stopping_voltage_uncertainty,-e_delta_v,c_over_lambda
0,640,5.21,0.3113,0.0001,-4.987576e-20,468425.715625
1,626,5.21,0.4073,0.0001,-6.525665e-20,478901.690096
2,604,5.21,0.4929,0.0001,-7.897129e-20,496345.129139
3,590,5.21,0.5669,0.0001,-9.082739e-20,508122.810169
4,570,5.21,0.6306,0.0001,-1.010333e-19,525951.680702